"""initial migration

Revision ID: 2e958dcfba83
Revises: 
Create Date: 2025-12-27 10:53:54.195940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e958dcfba83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('symbol', 'name', name='uq_asset_symbol_name')
    )
    op.create_table('etl_checkpoints',
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('last_processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_success_run_id', sa.UUID(), nullable=True),
    sa.Column('last_failure_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_failure_error', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('etl_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('triggered_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('raw_coingecko',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'payload_hash', name='uq_raw_coingecko_source_payload')
    )
    op.create_index(op.f('ix_raw_coingecko_payload_hash'), 'raw_coingecko', ['payload_hash'], unique=False)
    op.create_table('raw_coinpaprika',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'payload_hash', name='uq_raw_coinpaprika_source_payload')
    )
    op.create_index(op.f('ix_raw_coinpaprika_payload_hash'), 'raw_coinpaprika', ['payload_hash'], unique=False)
    op.create_table('raw_csv',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'payload_hash', name='uq_raw_csv_source_payload')
    )
    op.create_index(op.f('ix_raw_csv_payload_hash'), 'raw_csv', ['payload_hash'], unique=False)
    op.create_table('transform_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('raw_table', sa.Text(), nullable=False),
    sa.Column('raw_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('failed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_market_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('price_usd', sa.NUMERIC(), nullable=True),
    sa.Column('market_cap_usd', sa.NUMERIC(), nullable=True),
    sa.Column('volume_24h_usd', sa.NUMERIC(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'source', 'last_updated', name='uq_asset_market_source_time')
    )
    op.create_table('schema_drift_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.NUMERIC(), nullable=False),
    sa.Column('previous_signature', sa.Text(), nullable=True),
    sa.Column('new_signature', sa.Text(), nullable=True),
    sa.Column('warning_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['etl_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_drift_events')
    op.drop_table('asset_market_data')
    op.drop_table('transform_failures')
    op.drop_index(op.f('ix_raw_csv_payload_hash'), table_name='raw_csv')
    op.drop_table('raw_csv')
    op.drop_index(op.f('ix_raw_coinpaprika_payload_hash'), table_name='raw_coinpaprika')
    op.drop_table('raw_coinpaprika')
    op.drop_index(op.f('ix_raw_coingecko_payload_hash'), table_name='raw_coingecko')
    op.drop_table('raw_coingecko')
    op.drop_table('etl_runs')
    op.drop_table('etl_checkpoints')
    op.drop_table('assets')
    # ### end Alembic commands ###
